# ===================================================================
# CONFIGURAÇÕES DA APLICAÇÃO
# ===================================================================
spring.application.name=payment-service
server.port=8081

# 🛑 DESATIVAR CONTROLE AUTOMÁTICO DO DOCKER COMPOSE
# (Evita que o Spring derrube a aplicação se o Docker Desktop estiver fechado)
spring.docker.compose.enabled=false
spring.docker.compose.skip.in-tests=false

# ===================================================================
# CONFIGURAÇÕES DO APACHE KAFKA (CONEXÃO)
# ===================================================================
# Endereço do servidor central do Kafka onde os dois serviços vão se conectar
spring.kafka.bootstrap-servers=localhost:9092

# Configurações do Produtor (O Pagamento envia mensagens como String/JSON)
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

# Caso o Pagamento também precise escutar alguma resposta futura
spring.kafka.consumer.group-id=payment-group
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer